### ISSUE TITLE
NPE in annotation processing

### ISSUE THREAD

**Issue by kthoms** [eclipse/xtext-lib#81]
After a git pull I got several NPEs in the error log of that kind:

```
Error during annotation processing:
java.lang.NullPointerException: Name is null
	at java.lang.Enum.valueOf(Enum.java:236)
	at org.eclipse.xtend.lib.annotations.AccessorType.valueOf(AccessorType.java:10)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor$Util$2.apply(AccessorsProcessor.java:135)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor$Util$2.apply(AccessorsProcessor.java:132)
	at org.eclipse.xtext.xbase.lib.internal.FunctionDelegate.apply(FunctionDelegate.java:42)
	at com.google.common.collect.Lists$TransformingRandomAccessList$1.transform(Lists.java:651)
	at com.google.common.collect.TransformedIterator.next(TransformedIterator.java:47)
	at org.eclipse.xtext.xbase.lib.IteratorExtensions.findFirst(IteratorExtensions.java:107)
	at org.eclipse.xtext.xbase.lib.IterableExtensions.findFirst(IterableExtensions.java:80)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor$Util.getGetterType(AccessorsProcessor.java:146)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor$Util.shouldAddGetter(AccessorsProcessor.java:118)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor._transform(AccessorsProcessor.java:353)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor$3.accept(AccessorsProcessor.java:383)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor$3.accept(AccessorsProcessor.java:380)
	at com.google.common.collect.Iterables$4.lambda$forEach$0(Iterables.java:581)
	at com.google.common.collect.Iterables$5.lambda$forEach$0(Iterables.java:624)
	at com.google.common.collect.ImmutableList.forEach(ImmutableList.java:408)
	at com.google.common.collect.Iterables$5.forEach(Iterables.java:621)
	at com.google.common.collect.Iterables$4.forEach(Iterables.java:578)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor._transform(AccessorsProcessor.java:386)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor.transform(AccessorsProcessor.java:391)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor$1.accept(AccessorsProcessor.java:344)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor$1.accept(AccessorsProcessor.java:341)
	at java.lang.Iterable.forEach(Iterable.java:75)
	at org.eclipse.xtend.lib.annotations.AccessorsProcessor.doTransform(AccessorsProcessor.java:347)

```

**Comment by cdietrich** [comment]
what is the value? do you use mixed xtend lib versions?

**Comment by kthoms** [comment]
No mixing, this happens in my dev workspace.
Apparently a type's name is null, but I don't know why.

**Comment by cdietrich** [comment]
which project is affected?

**Comment by cdietrich** [comment]
but the lines make no sense to me.
which version do you use?

**Comment by kthoms** [comment]
2.14.0.v20180116-0209

**Comment by cdietrich** [comment]
that version is quite old
hmmm maybe it has to to with the java 8 change and possible updated linenumbers.

**Comment by kthoms** [comment]
will update of course now, but cleaning the projects made the error already disappear.

**Comment by cdietrich** [comment]
still need some hints on how to reproduce

**Comment by cdietrich** [comment]
@kthoms ok with close as not reproducible?

**Comment by kthoms** [comment]
Yes, I did not see this one again, so let's close it.
